apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tokenade-data-pvc
  namespace: tokenade
  labels:
    app.kubernetes.io/name: tokenade
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
