"""Tests for browser extension payload structure and loader interoperability."""

import json
import tempfile
from pathlib import Path

import pytest
from tokenade.core.importer.session_packager import SessionPackager
from tokenade.core.importer.session_loader import SessionLoader
from tokenade.sdk import TokenadeClient


def test_extension_v3_payload_schema():
    """Verify that an export generated by the browser extension complies with v3 schema."""
    # Synthetic export directly matching extension popup.js output
    extension_export = {
        "version": "3.0",
        "site_name": "example.com",
        "auth_status": "unknown",
        "created_at": "2026-08-17T12:00:00Z",
        "source_device": {
            "browser": "chrome-extension",
            "profile": "active-tab",
            "platform": "Linux x86_64",
            "hostname": "anonymous",
        },
        "cookies": [
            {
                "name": "session_id",
                "value": "xyz123abc",
                "domain": ".example.com",
                "path": "/",
                "secure": True,
                "httpOnly": True,
                "sameSite": "Lax",
                "expires": 1800000000,
            }
        ],
        "tokens": [],
        "storage": {
            "local": {
                "https://example.com": {
                    "theme": "dark",
                    "user_token": "token_val_999",
                }
            },
            "session": {
                "https://example.com": {
                    "tab_state": "active_chat_1",
                }
            },
        },
        "local_storage": {
            "example.com:theme": "dark",
            "example.com:user_token": "token_val_999",
        },
        "fingerprint": None,
        "tls_profile": None,
        "metadata": {
            "extraction_method": "extension",
            "source": "tokenade-extension",
            "source_format": "tokenade",
            "domain": "example.com",
            "page_url": "https://example.com/app",
            "exported_at": "2026-08-17T12:00:00Z",
            "cookie_count": 1,
            "local_storage_count": 2,
            "session_storage_count": 1,
        },
    }

    with tempfile.NamedTemporaryFile(suffix=".tokenade", mode="w", delete=False) as f:
        json.dump(extension_export, f)
        tmp_path = f.name

    try:
        # 1. Test SessionPackager load & validate
        packager = SessionPackager()
        loaded = packager.load(tmp_path)
        assert loaded is not None
        assert loaded["version"] == "3.0"
        assert loaded["site_name"] == "example.com"
        assert len(loaded["cookies"]) == 1
        assert "https://example.com" in loaded["storage"]["local"]
        assert "https://example.com" in loaded["storage"]["session"]

        # 2. Test TokenadeClient SDK load & health check
        client = TokenadeClient()
        sdk_loaded = client.load(tmp_path)
        assert sdk_loaded["site_name"] == "example.com"
        health = client.health_check(tmp_path)
        assert health["health_score"] >= 0.5

        # 3. Test SessionLoader storage map resolution
        loader = SessionLoader(loaded)
        ls_pairs = loader._local_storage_by_origin(loaded)
        ss_pairs = loader._session_storage_by_origin(loaded)
        ls_dict = {orig: data for orig, data in ls_pairs}
        ss_dict = {orig: data for orig, data in ss_pairs}
        assert "https://example.com" in ls_dict
        assert "https://example.com" in ss_dict
        assert ls_dict["https://example.com"]["user_token"] == "token_val_999"
        assert ss_dict["https://example.com"]["tab_state"] == "active_chat_1"

    finally:
        Path(tmp_path).unlink(missing_ok=True)


def test_extension_webcrypto_encrypted_payload_interop():
    """Verify that WebCrypto AES-256-GCM binary encrypted exports can be decrypted by TokenadeEncryptor."""
    import subprocess
    import shutil
    from tokenade.core.crypto.encryptor import TokenadeEncryptor

    node = shutil.which("node")
    if not node:
        pytest.skip("node not available")

    secret = "interop-test-secret-456!"
    js_code = f"""
    const {{ TokenadeWebCrypto }} = require('./extension/crypto.js');
    (async () => {{
        const session = {{
            version: "3.0.0",
            site_name: "encrypted-site.com",
            cookies: [{{ name: "auth_token", value: "secret_tok_99", domain: ".encrypted-site.com", path: "/" }}],
            storage: {{ local: {{ "https://encrypted-site.com": {{ user_id: "u_100" }} }} }}
        }};
        const bytes = await TokenadeWebCrypto.encrypt(JSON.stringify(session), "{secret}");
        process.stdout.write(Buffer.from(bytes));
    }})();
    """

    res = subprocess.run([node, "-e", js_code], capture_output=True, check=True)
    encrypted_bytes = res.stdout

    # Decrypt via core TokenadeEncryptor
    encryptor = TokenadeEncryptor()
    decrypted_raw = encryptor.decrypt(encrypted_bytes, secret)
    session = json.loads(decrypted_raw.decode("utf-8"))

    assert session["site_name"] == "encrypted-site.com"
    assert session["cookies"][0]["name"] == "auth_token"
    assert session["cookies"][0]["value"] == "secret_tok_99"
    assert session["storage"]["local"]["https://encrypted-site.com"]["user_id"] == "u_100"


def test_extension_bundle_packages_all_v14_assets(tmp_path):
    """Verify that ExtensionBundler builds valid Chrome .zip and Firefox .xpi with all v1.4 assets."""
    import zipfile
    from tokenade.core.browser.extension_bundler import ExtensionBundler

    out_dir = tmp_path / "bundles"
    out_dir.mkdir(parents=True)
    chrome_zip_path = out_dir / "chrome.zip"
    firefox_xpi_path = out_dir / "firefox.xpi"

    bundler = ExtensionBundler(source_dir=Path("extension"))
    valid, errors = bundler.validate_source()
    assert valid is True, f"Validation errors: {errors}"

    chrome_zip = bundler.build_chrome_zip(chrome_zip_path)
    firefox_xpi = bundler.build_firefox_xpi(firefox_xpi_path)

    assert chrome_zip.exists()
    assert firefox_xpi.exists()

    with zipfile.ZipFile(chrome_zip) as z:
        names = set(z.namelist())
        assert "manifest.json" in names
        assert "crypto.js" in names
        assert "popup.html" in names
        assert "popup.js" in names
        assert "background.js" in names
        assert "content.js" in names

    with zipfile.ZipFile(firefox_xpi) as z:
        names = set(z.namelist())
        assert "manifest.json" in names
        assert "crypto.js" in names
        assert "popup.html" in names
        assert "popup.js" in names
