"""Tests for browser extension payload structure and loader interoperability."""

import json
import tempfile
from pathlib import Path

import pytest
from tokenade.core.importer.session_packager import SessionPackager
from tokenade.core.importer.session_loader import SessionLoader
from tokenade.sdk import TokenadeClient


def test_extension_v3_payload_schema():
    """Verify that an export generated by the browser extension complies with v3 schema."""
    # Synthetic export directly matching extension popup.js output
    extension_export = {
        "version": "3.0",
        "site_name": "example.com",
        "auth_status": "unknown",
        "created_at": "2026-08-17T12:00:00Z",
        "source_device": {
            "browser": "chrome-extension",
            "profile": "active-tab",
            "platform": "Linux x86_64",
            "hostname": "anonymous",
        },
        "cookies": [
            {
                "name": "session_id",
                "value": "xyz123abc",
                "domain": ".example.com",
                "path": "/",
                "secure": True,
                "httpOnly": True,
                "sameSite": "Lax",
                "expires": 1800000000,
            }
        ],
        "tokens": [],
        "storage": {
            "local": {
                "https://example.com": {
                    "theme": "dark",
                    "user_token": "token_val_999",
                }
            },
            "session": {
                "https://example.com": {
                    "tab_state": "active_chat_1",
                }
            },
        },
        "local_storage": {
            "example.com:theme": "dark",
            "example.com:user_token": "token_val_999",
        },
        "fingerprint": None,
        "tls_profile": None,
        "metadata": {
            "extraction_method": "extension",
            "source": "tokenade-extension",
            "source_format": "tokenade",
            "domain": "example.com",
            "page_url": "https://example.com/app",
            "exported_at": "2026-08-17T12:00:00Z",
            "cookie_count": 1,
            "local_storage_count": 2,
            "session_storage_count": 1,
        },
    }

    with tempfile.NamedTemporaryFile(suffix=".tokenade", mode="w", delete=False) as f:
        json.dump(extension_export, f)
        tmp_path = f.name

    try:
        # 1. Test SessionPackager load & validate
        packager = SessionPackager()
        loaded = packager.load(tmp_path)
        assert loaded is not None
        assert loaded["version"] == "3.0"
        assert loaded["site_name"] == "example.com"
        assert len(loaded["cookies"]) == 1
        assert "https://example.com" in loaded["storage"]["local"]
        assert "https://example.com" in loaded["storage"]["session"]

        # 2. Test TokenadeClient SDK load & health check
        client = TokenadeClient()
        sdk_loaded = client.load(tmp_path)
        assert sdk_loaded["site_name"] == "example.com"
        health = client.health_check(tmp_path)
        assert health["health_score"] >= 0.5

        # 3. Test SessionLoader storage map resolution
        loader = SessionLoader(loaded)
        ls_pairs = loader._local_storage_by_origin(loaded)
        ss_pairs = loader._session_storage_by_origin(loaded)
        ls_dict = {orig: data for orig, data in ls_pairs}
        ss_dict = {orig: data for orig, data in ss_pairs}
        assert "https://example.com" in ls_dict
        assert "https://example.com" in ss_dict
        assert ls_dict["https://example.com"]["user_token"] == "token_val_999"
        assert ss_dict["https://example.com"]["tab_state"] == "active_chat_1"

    finally:
        Path(tmp_path).unlink(missing_ok=True)
