"""
Static HTML marketplace page generator for plugins.

Generates a self-contained HTML page from cached registry data.
No server needed — just open the file in a browser.
"""

import json
import logging
import html as html_mod
from pathlib import Path
from typing import Dict, List

logger = logging.getLogger(__name__)

HTML_TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>TOKENADE_TITLE</title>
<style>
:root {
    --bg: #0d1117;
    --surface: #161b22;
    --surface2: #21262d;
    --border: #30363d;
    --text: #e6edf3;
    --text-dim: #8b949e;
    --accent: #58a6ff;
    --green: #3fb950;
    --yellow: #d29922;
    --red: #f85149;
    --purple: #bc8cff;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: var(--bg); color: var(--text);
    line-height: 1.6; padding: 20px;
}
.container { max-width: 1200px; margin: 0 auto; }
header { text-align: center; padding: 40px 20px; }
header h1 { font-size: 2.5rem; margin-bottom: 10px; }
header p { color: var(--text-dim); font-size: 1.1rem; }
.search-bar {
    display: flex; gap: 10px; margin: 30px 0;
    justify-content: center; flex-wrap: wrap;
}
.search-bar input {
    padding: 12px 20px; border-radius: 8px;
    border: 1px solid var(--border); background: var(--surface);
    color: var(--text); font-size: 1rem; width: 400px; max-width: 100%;
}
.search-bar input:focus { outline: none; border-color: var(--accent); }
.filters {
    display: flex; gap: 10px; flex-wrap: wrap;
    justify-content: center; margin-bottom: 30px;
}
.filter-btn {
    padding: 6px 16px; border-radius: 20px;
    border: 1px solid var(--border); background: var(--surface);
    color: var(--text-dim); cursor: pointer; font-size: 0.9rem;
    transition: all 0.2s;
}
.filter-btn:hover, .filter-btn.active {
    border-color: var(--accent); color: var(--accent);
    background: rgba(88,166,255,0.1);
}
.grid {
    display: grid; grid-template-columns: repeat(auto-fill, minmax(350px, 1fr));
    gap: 20px; margin-top: 20px;
}
.card {
    background: var(--surface); border: 1px solid var(--border);
    border-radius: 12px; padding: 24px; transition: all 0.2s;
}
.card:hover { border-color: var(--accent); transform: translateY(-2px); }
.card-header { display: flex; justify-content: space-between; align-items: start; }
.card-title { font-size: 1.2rem; font-weight: 600; }
.card-version { color: var(--text-dim); font-size: 0.85rem; }
.card-desc { color: var(--text-dim); margin: 12px 0; font-size: 0.95rem; }
.card-meta { display: flex; gap: 16px; flex-wrap: wrap; font-size: 0.85rem; color: var(--text-dim); }
.card-meta span { display: flex; align-items: center; gap: 4px; }
.rating { color: var(--yellow); }
.verified { color: var(--green); }
.downloads { color: var(--purple); }
.card-tags { display: flex; gap: 6px; flex-wrap: wrap; margin-top: 12px; }
.tag {
    padding: 2px 8px; border-radius: 4px; font-size: 0.8rem;
    background: var(--surface2); color: var(--text-dim);
}
.card-actions { margin-top: 16px; display: flex; gap: 10px; }
.btn {
    padding: 8px 16px; border-radius: 6px; border: none;
    cursor: pointer; font-size: 0.9rem; font-weight: 500;
    transition: all 0.2s;
}
.btn-primary { background: var(--accent); color: #fff; }
.btn-primary:hover { background: #79c0ff; }
.btn-secondary { background: var(--surface2); color: var(--text); border: 1px solid var(--border); }
.btn-secondary:hover { border-color: var(--accent); }
.empty { text-align: center; padding: 60px 20px; color: var(--text-dim); }
footer { text-align: center; padding: 40px 20px; color: var(--text-dim); font-size: 0.85rem; }
</style>
</head>
<body>
<div class="container">
    <header>
        <h1>TOKENADE_TITLE</h1>
        <p>Extend Tokenade with plugins for authentication, export formats, and more</p>
    </header>

    <div class="search-bar">
        <input type="text" id="search" placeholder="Search plugins by name, description, author, or tag..." autofocus>
    </div>

    <div class="filters" id="filters"></div>

    <div class="grid" id="plugins"></div>

    <div class="empty" id="empty" style="display:none">No plugins found matching your search.</div>

    <footer>
        <p>Generated by <strong>Tokenade</strong> &mdash; <code>tokenade plugin browse</code></p>
        <p>Registry: <a href="https://tokenade-plugins.pages.dev" style="color:var(--accent)">tokenade-plugins.pages.dev</a></p>
    </footer>
</div>

<script>
var ALL_PLUGINS = TOKENADE_PLUGINS;
var CATEGORIES = TOKENADE_CATEGORIES;

var activeCategory = null;
var searchQuery = '';

function renderFilters() {
    var el = document.getElementById('filters');
    var html = '<button class="filter-btn active" onclick="setCategory(null)">All</button>';
    CATEGORIES.forEach(function(c) {
        var count = ALL_PLUGINS.filter(function(p) { return p.category === c.name; }).length;
        html += '<button class="filter-btn" onclick="setCategory(\'' + c.name + '\')">' + (c.icon || '') + ' ' + c.name + ' (' + count + ')</button>';
    });
    el.innerHTML = html;
}

function setCategory(cat) {
    activeCategory = cat;
    renderFilters();
    renderPlugins();
}

function renderPlugins() {
    var query = searchQuery.toLowerCase();
    var filtered = ALL_PLUGINS;

    if (activeCategory) {
        filtered = filtered.filter(function(p) { return p.category === activeCategory; });
    }

    if (query) {
        filtered = filtered.filter(function(p) {
            return (p.name || '').toLowerCase().indexOf(query) !== -1 ||
                (p.description || '').toLowerCase().indexOf(query) !== -1 ||
                (p.author || '').toLowerCase().indexOf(query) !== -1 ||
                (p.tags || []).some(function(t) { return t.toLowerCase().indexOf(query) !== -1; });
        });
    }

    filtered.sort(function(a, b) { return (b.rating || 0) - (a.rating || 0) || (b.downloads || 0) - (a.downloads || 0); });

    var el = document.getElementById('plugins');
    var empty = document.getElementById('empty');

    if (filtered.length === 0) {
        el.innerHTML = '';
        empty.style.display = 'block';
        return;
    }
    empty.style.display = 'none';

    el.innerHTML = filtered.map(function(p) {
        var stars = p.rating ? '<span class="rating">&#9733; ' + p.rating.toFixed(1) + ' (' + (p.review_count || 0) + ')</span>' : '';
        var verified = p.verified ? ' <span class="verified" title="Verified">&#10003;</span>' : '';
        var tags = (p.tags || []).map(function(t) { return '<span class="tag">' + esc(t) + '</span>'; }).join('');
        return '<div class="card">' +
            '<div class="card-header"><div>' +
            '<div class="card-title">' + esc(p.name) + verified + '</div>' +
            '<div class="card-version">v' + esc(p.version || '?') + '</div>' +
            '</div></div>' +
            '<div class="card-desc">' + esc(p.description || '') + '</div>' +
            '<div class="card-meta">' + stars +
            ' <span class="downloads">&#8595; ' + formatNum(p.downloads || 0) + '</span>' +
            ' <span>by ' + esc(p.author || 'unknown') + '</span></div>' +
            '<div class="card-tags">' + tags + '</div>' +
            '<div class="card-actions">' +
            '<button class="btn btn-primary" onclick="installPlugin(\'' + esc(p.name) + '\')">Install</button>' +
            '<button class="btn btn-secondary" onclick="copyInstall(\'' + esc(p.name) + '\')">Copy command</button>' +
            '</div></div>';
    }).join('');
}

function esc(s) { return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'); }
function formatNum(n) { return n >= 1000 ? (n/1000).toFixed(1) + 'k' : n; }

function installPlugin(name) {
    var cmd = 'tokenade plugin install ' + name;
    navigator.clipboard.writeText(cmd).then(function() {
        alert('Copied to clipboard:\n' + cmd + '\n\nRun this in your terminal to install.');
    }).catch(function() {
        alert('To install, run:\n' + cmd);
    });
}

function copyInstall(name) {
    var cmd = 'tokenade plugin install ' + name;
    navigator.clipboard.writeText(cmd).then(function() { alert('Copied!'); });
}

document.getElementById('search').addEventListener('input', function(e) {
    searchQuery = e.target.value;
    renderPlugins();
});

renderFilters();
renderPlugins();
</script>
</body>
</html>"""


def generate_marketplace_html(
    plugins: List[Dict],
    categories: List[Dict],
    output_path: str,
    title: str = "Tokenade Plugin Marketplace",
) -> str:
    """Generate a static HTML marketplace page."""
    plugins_json = json.dumps(plugins)
    categories_json = json.dumps(categories)

    html_content = HTML_TEMPLATE
    html_content = html_content.replace("TOKENADE_TITLE", html_mod.escape(title))
    html_content = html_content.replace("TOKENADE_PLUGINS", plugins_json)
    html_content = html_content.replace("TOKENADE_CATEGORIES", categories_json)

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(html_content, encoding="utf-8")
    logger.info(f"Marketplace page generated: {output}")
    return str(output)
